name: ride_together
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter:
    sdk: flutter
  flutter_foreground_task: ^9.2.0
  flutter_polyline_points: ^3.1.0
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  mapbox_maps_flutter: ^2.17.0
  mapbox_search: ^4.3.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
